# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MobileSocialBlogApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MobileSocialBlogApp
  # pod 'Firebase/Analytics'
  # Add the pods for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage', '6.12.0'
  target 'MobileSocialBlogAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MobileSocialBlogAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
