//
//  SignupInjector.swift
//  MobileSocialBlogApp
//
//  Created by Andre Insigne on 27/11/2019.
//  Copyright © 2019 Andre Insigne. All rights reserved.
//


import Foundation


/// injector protocol template for injection of the services and data
protocol SignupInjector {
    func inject(viewController: SignupViewController)
}
/// injector implementation of the protocol template for injection
class SignupInjectorImplementation: SignupInjector {

    /// injects the SignupViewController generated with the services and the presenter used
    /// data
    /// - Parameter viewController: SignupViewController generated by the mvp template
    func inject(viewController: SignupViewController) {
     
 
        let data = DataInjector().getData()
        let services = ServicesInjector(data: data)
        let presenter = SignupPresenterImplementation(view: viewController, apiManager : services.getAPI() , authManager : services.getAuth())
        
        viewController.presenter = presenter
    }
}
