//
//  DiscoverInjector.swift
//  MobileSocialBlogApp
//
//  Created by Andre Insigne on 30/11/2019.
//  Copyright © 2019 Andre Insigne. All rights reserved.
//


import Foundation


/// injector protocol template for injection of the services and data
protocol DiscoverInjector {
    func inject(viewController: DiscoverViewController)
}
/// injector implementation of the protocol template for injection
class DiscoverInjectorImplementation: DiscoverInjector {

    /// injects the DiscoverViewController generated with the services and the presenter used
    /// data
    /// - Parameter viewController: DiscoverViewController generated by the mvp template
    func inject(viewController: DiscoverViewController) {
     
 
        let data = DataInjector().getData()
        let services = ServicesInjector(data: data)
        let presenter = DiscoverPresenterImplementation(view: viewController, apiManager : services.getAPI() , authManager : services.getAuth())
        
        viewController.presenter = presenter
    }
}
