//
//  FeedDetailsInjector.swift
//  MobileSocialBlogApp
//
//  Created by Andre Insigne on 29/11/2019.
//  Copyright © 2019 Andre Insigne. All rights reserved.
//


import Foundation


/// injector protocol template for injection of the services and data
protocol FeedDetailsInjector {
    func inject(viewController: FeedDetailsViewController)
}
/// injector implementation of the protocol template for injection
class FeedDetailsInjectorImplementation: FeedDetailsInjector {

    /// injects the FeedDetailsViewController generated with the services and the presenter used
    /// data
    /// - Parameter viewController: FeedDetailsViewController generated by the mvp template
    func inject(viewController: FeedDetailsViewController) {
     
 
        let data = DataInjector().getData()
        let services = ServicesInjector(data: data)
        let presenter = FeedDetailsPresenterImplementation(view: viewController, apiManager : services.getAPI() , authManager : services.getAuth())
        
        viewController.presenter = presenter
    }
}
