//
//  OptionalSignupInjector.swift
//  MobileSocialBlogApp
//
//  Created by Andre Insigne on 27/11/2019.
//  Copyright © 2019 Andre Insigne. All rights reserved.
//


import Foundation


/// injector protocol template for injection of the services and data
protocol OptionalSignupInjector {
    func inject(viewController: OptionalSignupViewController)
}
/// injector implementation of the protocol template for injection
class OptionalSignupInjectorImplementation: OptionalSignupInjector {

    /// injects the OptionalSignupViewController generated with the services and the presenter used
    /// data
    /// - Parameter viewController: OptionalSignupViewController generated by the mvp template
    func inject(viewController: OptionalSignupViewController) {
     
 
        let data = DataInjector().getData()
        let services = ServicesInjector(data: data)
        let presenter = OptionalSignupPresenterImplementation(view: viewController, apiManager : services.getAPI() , authManager : services.getAuth())
        
        viewController.presenter = presenter
    }
}
