//
//  SampleInjector.swift
//  MobileSocialBlogApp
//
//  Created by Andre Insigne on 25/11/2019.
//  Copyright © 2019 Andre Insigne. All rights reserved.
//


import Foundation


/// injector protocol template for injection of the services and data
protocol SampleInjector {
    func inject(viewController: SampleViewController)
}
/// injector implementation of the protocol template for injection
class SampleInjectorImplementation: SampleInjector {

    /// injects the SampleViewController generated with the services and the presenter used
    /// data
    /// - Parameter viewController: SampleViewController generated by the mvp template
    func inject(viewController: SampleViewController) {
     
 
        let data = DataInjector().getData()
        let services = ServicesInjector(data: data)
        let presenter = SamplePresenterImplementation(view: viewController, apiManager : services.getAPI() , authManager : services.getAuth())
        
        viewController.presenter = presenter
    }
}
